package hello;
// Generated 2012. 2. 13 오후 6:12:21 by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="MESSAGE"
    ,schema="PUBLIC"
)
public class Message  implements java.io.Serializable {


     private Long id;
     private Message nextMessage;
     private String text;

    public Message() {
    }

    public Message(Message nextMessage, String text) {
       this.nextMessage = nextMessage;
       this.text = text;
    }
   
     @GenericGenerator(name="generator", strategy="increment")@Id @GeneratedValue(generator="generator")

    
    @Column(name="ID", nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NEXT_MESSAGE_ID")
    public Message getNextMessage() {
        return this.nextMessage;
    }
    
    public void setNextMessage(Message nextMessage) {
        this.nextMessage = nextMessage;
    }

    
    @Column(name="MESSAGE_TEXT")
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


