package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SecondaryTable;
import javax.persistence.Table;

/**
 * Caption generated by hbm2java
 */
@Entity
@Table(name="K_CAPTION"
    ,schema="KBSTRI"
)
@SecondaryTable(name="K_RELATED_CAPTION")
public class Caption  implements java.io.Serializable {

    // Fields    

     private Integer captionId;
     private Content content;
     private String fileFormat;
     private String captionFilePath;
     private String captionLanguageKind;

     // Constructors

    /** default constructor */
    public Caption() {
    }

	/** minimal constructor */
    public Caption(Integer captionId) {
        this.captionId = captionId;
    }
    /** full constructor */
    public Caption(Integer captionId, Content content, String fileFormat, String captionFilePath, String captionLanguageKind) {
       this.captionId = captionId;
       this.content = content;
       this.fileFormat = fileFormat;
       this.captionFilePath = captionFilePath;
       this.captionLanguageKind = captionLanguageKind;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CAPTION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getCaptionId() {
        return this.captionId;
    }
    
    public void setCaptionId(Integer captionId) {
        this.captionId = captionId;
    }
    @ManyToOne
    @JoinColumn(table="K_RELATED_CAPTION",name="CONTENT_ID")
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="FILE_FORMAT", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getFileFormat() {
        return this.fileFormat;
    }
    
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }
    
    @Column(name="CAPTION_FILE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getCaptionFilePath() {
        return this.captionFilePath;
    }
    
    public void setCaptionFilePath(String captionFilePath) {
        this.captionFilePath = captionFilePath;
    }
    
    @Column(name="CAPTION_LANGUAGE_KIND", unique=false, nullable=true, insertable=true, updatable=true)
    public String getCaptionLanguageKind() {
        return this.captionLanguageKind;
    }
    
    public void setCaptionLanguageKind(String captionLanguageKind) {
        this.captionLanguageKind = captionLanguageKind;
    }




}


