package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Channel generated by hbm2java
 */
@Entity
@Table(name="K_CHANNEL"
    ,schema="KBSTRI"
)
//@JsonIgnoreProperties("hibernateLazyInitializer")
public class Channel  implements java.io.Serializable {

    // Fields    

     private String channelCode;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String mediaName;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String channelName;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String channelGrade;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String channelDescription;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String channelImagePath;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String liveStreamUrl;
     @org.codehaus.jackson.annotate.JsonIgnore
     private String channelAuthority;

     // Constructors

    /** default constructor */
    public Channel() {
    }

	/** minimal constructor */
    public Channel(String channelCode) {
        this.channelCode = channelCode;
    }
    /** full constructor */
    public Channel(String channelCode, String mediaName, String channelName, String channelGrade, String channelDescription, String channelImagePath, String liveStreamUrl, String channelAuthority) {
       this.channelCode = channelCode;
       this.mediaName = mediaName;
       this.channelName = channelName;
       this.channelGrade = channelGrade;
       this.channelDescription = channelDescription;
       this.channelImagePath = channelImagePath;
       this.liveStreamUrl = liveStreamUrl;
       this.channelAuthority = channelAuthority;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CHANNEL_CODE", unique=false, nullable=false, insertable=true, updatable=true, length=2)
    public String getChannelCode() {
        return this.channelCode;
    }
    
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }
    
    @Column(name="MEDIA_NAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMediaName() {
        return this.mediaName;
    }
    
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName;
    }
    
    @Column(name="CHANNEL_NAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelName() {
        return this.channelName;
    }
    
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
    
    @Column(name="CHANNEL_GRADE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelGrade() {
        return this.channelGrade;
    }
    
    public void setChannelGrade(String channelGrade) {
        this.channelGrade = channelGrade;
    }
    
    @Column(name="CHANNEL_DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelDescription() {
        return this.channelDescription;
    }
    
    public void setChannelDescription(String channelDescription) {
        this.channelDescription = channelDescription;
    }
    
    @Column(name="CHANNEL_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelImagePath() {
        return this.channelImagePath;
    }
    
    public void setChannelImagePath(String channelImagePath) {
        this.channelImagePath = channelImagePath;
    }
    
    @Column(name="LIVE_STREAM_URL", unique=false, nullable=true, insertable=true, updatable=true)
    public String getLiveStreamUrl() {
        return this.liveStreamUrl;
    }
    
    public void setLiveStreamUrl(String liveStreamUrl) {
        this.liveStreamUrl = liveStreamUrl;
    }
    
    @Column(name="CHANNEL_AUTHORITY", unique=false, nullable=true, insertable=true, updatable=true, length=2)
    public String getChannelAuthority() {
        return this.channelAuthority;
    }
    
    public void setChannelAuthority(String channelAuthority) {
        this.channelAuthority = channelAuthority;
    }
    




}


