package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChannelItemId generated by hbm2java
 */
@Embeddable
public class ChannelItemId  implements java.io.Serializable {

    // Fields    

     private Integer channelId;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public ChannelItemId() {
    }

    /** full constructor */
    public ChannelItemId(Integer channelId, Integer contentId) {
       this.channelId = channelId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="CHANNEL_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getChannelId() {
        return this.channelId;
    }
    
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


