package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorrectAnswer generated by hbm2java
 */
@Entity
@Table(name="K_CORRECT_ANSWER"
    ,schema="KBSTRI"
)
public class CorrectAnswer  implements java.io.Serializable {

    // Fields    

     private Integer questionId;
     private Question question;
     private String answer;

     // Constructors

    /** default constructor */
    public CorrectAnswer() {
    }

	/** minimal constructor */
    public CorrectAnswer(Integer questionId, Question question) {
        this.questionId = questionId;
        this.question = question;
    }
    /** full constructor */
    public CorrectAnswer(Integer questionId, Question question, String answer) {
       this.questionId = questionId;
       this.question = question;
       this.answer = answer;
    }
   
    // Property accessors
     @Id
    
    @Column(name="QUESTION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="QUESTION_ID", unique=true, nullable=false, insertable=false, updatable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    
    @Column(name="ANSWER", unique=false, nullable=true, insertable=true, updatable=true)
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


