package com.mindwareworks.kbs.model;

// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CorrectAnswer generated by hbm2java
 */

@Entity
@Table(name = "K_CORRECT_ANSWER", schema = "KBSTRI")
@org.hibernate.annotations.BatchSize(size=10)
public class CorrectAnswer implements java.io.Serializable {

	// Fields

	private Integer questionId;
	private String answer;

	// Constructors

	/** default constructor */
	public CorrectAnswer() {
	}

	// Property accessors
	@Id
	@Column(name = "QUESTION_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "ANSWER", unique = false, nullable = true, insertable = true, updatable = true)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String toString() {
		return "answer='" + this.answer + "'";
	}

}
