package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Encoding generated by hbm2java
 */
@Entity
@Table(name="K_ENCODING"
    ,schema="KBSTRI"
)
public class Encoding  implements java.io.Serializable {

    // Fields    

     private Integer encodingId;
     private String fileFormat;

     // Constructors

    /** default constructor */
    public Encoding() {
    }

	
   
    // Property accessors
     @Id
    
    @Column(name="ENCODING_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getEncodingId() {
        return this.encodingId;
    }
    
    public void setEncodingId(Integer encodingId) {
        this.encodingId = encodingId;
    }


    @Column(name="file_format")
	public String getFileFormat() {
		return fileFormat;
	}



	public void setFileFormat(String fileFormat) {
		this.fileFormat = fileFormat;
	}
    
   




}


