package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LiveCaptionId generated by hbm2java
 */
@Embeddable
public class LiveCaptionId  implements java.io.Serializable {

    // Fields    

     private Integer captionSeq;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public LiveCaptionId() {
    }

    /** full constructor */
    public LiveCaptionId(Integer captionSeq, Integer contentId) {
       this.captionSeq = captionSeq;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="CAPTION_SEQ", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getCaptionSeq() {
        return this.captionSeq;
    }
    
    public void setCaptionSeq(Integer captionSeq) {
        this.captionSeq = captionSeq;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


