package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Object generated by hbm2java
 */
@Entity
@Table(name="T_OBJECT"
    ,schema="KBSTRI"
)
public class Object  implements java.io.Serializable {

    // Fields    

     private Integer objid;
     private String objkey;
     private Integer objtype;
     private String objname;
     private String aboutme;
     private String title;
     private String phoneno;
     private Integer visitcount;
     private Date recentpostingdate;
     private Integer permission;
     private Integer articlecount;
     private Integer poscount;
     private Integer photocount;
     private Integer newarticlecount;
     private Integer filecount;
     private Integer textcount;
     private Integer contentscount;
     private Integer activitypoint;
     private Integer urlcount;
     private Integer statuscode;
     private Boolean isexistsmsg;
     private Date regdate;
     private String nationalcode;
     private Integer domainid;
     private Integer orgid;
     private Set<ProgramCode> programCodes = new HashSet<ProgramCode>(0);
     private Set<Member> members = new HashSet<Member>(0);
     private Set<Article> articles = new HashSet<Article>(0);
     private Set<ObjectCategory> objectCategories = new HashSet<ObjectCategory>(0);

     // Constructors

    /** default constructor */
    public Object() {
    }

	/** minimal constructor */
    public Object(Integer objid, Integer objtype, Integer visitcount, Integer permission, Integer articlecount, Integer poscount, Integer photocount, Integer newarticlecount, Integer filecount, Integer textcount, Integer contentscount, Integer activitypoint, Integer urlcount, Integer statuscode, Boolean isexistsmsg, Date regdate) {
        this.objid = objid;
        this.objtype = objtype;
        this.visitcount = visitcount;
        this.permission = permission;
        this.articlecount = articlecount;
        this.poscount = poscount;
        this.photocount = photocount;
        this.newarticlecount = newarticlecount;
        this.filecount = filecount;
        this.textcount = textcount;
        this.contentscount = contentscount;
        this.activitypoint = activitypoint;
        this.urlcount = urlcount;
        this.statuscode = statuscode;
        this.isexistsmsg = isexistsmsg;
        this.regdate = regdate;
    }
    /** full constructor */
    public Object(Integer objid, String objkey, Integer objtype, String objname, String aboutme, String title, String phoneno, Integer visitcount, Date recentpostingdate, Integer permission, Integer articlecount, Integer poscount, Integer photocount, Integer newarticlecount, Integer filecount, Integer textcount, Integer contentscount, Integer activitypoint, Integer urlcount, Integer statuscode, Boolean isexistsmsg, Date regdate, String nationalcode, Integer domainid, Integer orgid, Set<ProgramCode> programCodes, Set<Member> members, Set<Article> articles, Set<ObjectCategory> objectCategories) {
       this.objid = objid;
       this.objkey = objkey;
       this.objtype = objtype;
       this.objname = objname;
       this.aboutme = aboutme;
       this.title = title;
       this.phoneno = phoneno;
       this.visitcount = visitcount;
       this.recentpostingdate = recentpostingdate;
       this.permission = permission;
       this.articlecount = articlecount;
       this.poscount = poscount;
       this.photocount = photocount;
       this.newarticlecount = newarticlecount;
       this.filecount = filecount;
       this.textcount = textcount;
       this.contentscount = contentscount;
       this.activitypoint = activitypoint;
       this.urlcount = urlcount;
       this.statuscode = statuscode;
       this.isexistsmsg = isexistsmsg;
       this.regdate = regdate;
       this.nationalcode = nationalcode;
       this.domainid = domainid;
       this.orgid = orgid;
       this.programCodes = programCodes;
       this.members = members;
       this.articles = articles;
       this.objectCategories = objectCategories;
    }
   
    // Property accessors
     @Id
    
    @Column(name="OBJID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getObjid() {
        return this.objid;
    }
    
    public void setObjid(Integer objid) {
        this.objid = objid;
    }
    
    @Column(name="OBJKEY", unique=true, nullable=true, insertable=true, updatable=true, length=64)
    public String getObjkey() {
        return this.objkey;
    }
    
    public void setObjkey(String objkey) {
        this.objkey = objkey;
    }
    
    @Column(name="OBJTYPE", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getObjtype() {
        return this.objtype;
    }
    
    public void setObjtype(Integer objtype) {
        this.objtype = objtype;
    }
    
    @Column(name="OBJNAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getObjname() {
        return this.objname;
    }
    
    public void setObjname(String objname) {
        this.objname = objname;
    }
    
    @Column(name="ABOUTME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getAboutme() {
        return this.aboutme;
    }
    
    public void setAboutme(String aboutme) {
        this.aboutme = aboutme;
    }
    
    @Column(name="TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="PHONENO", unique=false, nullable=true, insertable=true, updatable=true, length=32)
    public String getPhoneno() {
        return this.phoneno;
    }
    
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }
    
    @Column(name="VISITCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getVisitcount() {
        return this.visitcount;
    }
    
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }
    
    @Column(name="RECENTPOSTINGDATE", unique=false, nullable=true, insertable=true, updatable=true, length=7)
    public Date getRecentpostingdate() {
        return this.recentpostingdate;
    }
    
    public void setRecentpostingdate(Date recentpostingdate) {
        this.recentpostingdate = recentpostingdate;
    }
    
    @Column(name="PERMISSION", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getPermission() {
        return this.permission;
    }
    
    public void setPermission(Integer permission) {
        this.permission = permission;
    }
    
    @Column(name="ARTICLECOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getArticlecount() {
        return this.articlecount;
    }
    
    public void setArticlecount(Integer articlecount) {
        this.articlecount = articlecount;
    }
    
    @Column(name="POSCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getPoscount() {
        return this.poscount;
    }
    
    public void setPoscount(Integer poscount) {
        this.poscount = poscount;
    }
    
    @Column(name="PHOTOCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getPhotocount() {
        return this.photocount;
    }
    
    public void setPhotocount(Integer photocount) {
        this.photocount = photocount;
    }
    
    @Column(name="NEWARTICLECOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getNewarticlecount() {
        return this.newarticlecount;
    }
    
    public void setNewarticlecount(Integer newarticlecount) {
        this.newarticlecount = newarticlecount;
    }
    
    @Column(name="FILECOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getFilecount() {
        return this.filecount;
    }
    
    public void setFilecount(Integer filecount) {
        this.filecount = filecount;
    }
    
    @Column(name="TEXTCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getTextcount() {
        return this.textcount;
    }
    
    public void setTextcount(Integer textcount) {
        this.textcount = textcount;
    }
    
    @Column(name="CONTENTSCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentscount() {
        return this.contentscount;
    }
    
    public void setContentscount(Integer contentscount) {
        this.contentscount = contentscount;
    }
    
    @Column(name="ACTIVITYPOINT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getActivitypoint() {
        return this.activitypoint;
    }
    
    public void setActivitypoint(Integer activitypoint) {
        this.activitypoint = activitypoint;
    }
    
    @Column(name="URLCOUNT", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getUrlcount() {
        return this.urlcount;
    }
    
    public void setUrlcount(Integer urlcount) {
        this.urlcount = urlcount;
    }
    
    @Column(name="STATUSCODE", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getStatuscode() {
        return this.statuscode;
    }
    
    public void setStatuscode(Integer statuscode) {
        this.statuscode = statuscode;
    }
    
    @Column(name="ISEXISTSMSG", unique=false, nullable=false, insertable=true, updatable=true, length=1)
    public Boolean getIsexistsmsg() {
        return this.isexistsmsg;
    }
    
    public void setIsexistsmsg(Boolean isexistsmsg) {
        this.isexistsmsg = isexistsmsg;
    }
    
    @Column(name="REGDATE", unique=false, nullable=false, insertable=true, updatable=true, length=7)
    public Date getRegdate() {
        return this.regdate;
    }
    
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }
    
    @Column(name="NATIONALCODE", unique=false, nullable=true, insertable=true, updatable=true, length=5)
    public String getNationalcode() {
        return this.nationalcode;
    }
    
    public void setNationalcode(String nationalcode) {
        this.nationalcode = nationalcode;
    }
    
    @Column(name="DOMAINID", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getDomainid() {
        return this.domainid;
    }
    
    public void setDomainid(Integer domainid) {
        this.domainid = domainid;
    }
    
    @Column(name="ORGID", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getOrgid() {
        return this.orgid;
    }
    
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="object")
    public Set<ProgramCode> getProgramCodes() {
        return this.programCodes;
    }
    
    public void setProgramCodes(Set<ProgramCode> programCodes) {
        this.programCodes = programCodes;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="TObject")
    public Set<Member> getMembers() {
        return this.members;
    }
    
    public void setMembers(Set<Member> members) {
        this.members = members;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="object")
    public Set<Article> getArticles() {
        return this.articles;
    }
    
    public void setArticles(Set<Article> articles) {
        this.articles = articles;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="object")
    public Set<ObjectCategory> getObjectCategories() {
        return this.objectCategories;
    }
    
    public void setObjectCategories(Set<ObjectCategory> objectCategories) {
        this.objectCategories = objectCategories;
    }




}


