package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name="K_PROGRAM"
    ,schema="KBSTRI"
)
@org.hibernate.annotations.BatchSize(size=20)
public class Program  implements java.io.Serializable {

    // Fields    

     private Integer contentId;
     private ProgramCode programCode;
     private Content content;
     private String programId;
     private Boolean informationPossibleYn;
     private Integer programSequenceNumber;
     private String programTitle;
     private String originalTitle;
     private String programSubtitle;
     private String mainStory;
     private String mainImagePath;
     private String programDeliberationGrade;
     private String programGenre;
     private Integer durationSecond;
     private Set<Programming> programmings = new HashSet<Programming>(0);
     private Set<DailyRunning> dailyRunnings = new HashSet<DailyRunning>(0);

     // Constructors

    /** default constructor */
    public Program() {
    }

	/** minimal constructor */
    public Program(Integer contentId, Content content, String programId) {
        this.contentId = contentId;
        this.content = content;
        this.programId = programId;
    }
    /** full constructor */
    public Program(Integer contentId, ProgramCode programCode, Content content, String programId, Boolean informationPossibleYn, Integer programSequenceNumber, String programTitle, String originalTitle, String programSubtitle, String mainStory, String mainImagePath, String programDeliberationGrade, String programGenre, Integer durationSecond, Set<Programming> programmings, Set<DailyRunning> dailyRunnings) {
       this.contentId = contentId;
       this.programCode = programCode;
       this.content = content;
       this.programId = programId;
       this.informationPossibleYn = informationPossibleYn;
       this.programSequenceNumber = programSequenceNumber;
       this.programTitle = programTitle;
       this.originalTitle = originalTitle;
       this.programSubtitle = programSubtitle;
       this.mainStory = mainStory;
       this.mainImagePath = mainImagePath;
       this.programDeliberationGrade = programDeliberationGrade;
       this.programGenre = programGenre;
       this.durationSecond = durationSecond;
       this.programmings = programmings;
       this.dailyRunnings = dailyRunnings;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="PROGRAM_CODE", unique=false, nullable=true, insertable=true, updatable=true)
    public ProgramCode getProgramCode() {
        return this.programCode;
    }
    
    public void setProgramCode(ProgramCode programCode) {
        this.programCode = programCode;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=true, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="PROGRAM_ID", unique=false, nullable=false, insertable=true, updatable=true, length=20)
    public String getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(String programId) {
        this.programId = programId;
    }
    
    @Column(name="INFORMATION_POSSIBLE_YN", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public Boolean getInformationPossibleYn() {
        return this.informationPossibleYn;
    }
    
    public void setInformationPossibleYn(Boolean informationPossibleYn) {
        this.informationPossibleYn = informationPossibleYn;
    }
    
    @Column(name="PROGRAM_SEQUENCE_NUMBER", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getProgramSequenceNumber() {
        return this.programSequenceNumber;
    }
    
    public void setProgramSequenceNumber(Integer programSequenceNumber) {
        this.programSequenceNumber = programSequenceNumber;
    }
    
    @Column(name="PROGRAM_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getProgramTitle() {
        return this.programTitle;
    }
    
    public void setProgramTitle(String programTitle) {
        this.programTitle = programTitle;
    }
    
    @Column(name="ORIGINAL_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getOriginalTitle() {
        return this.originalTitle;
    }
    
    public void setOriginalTitle(String originalTitle) {
        this.originalTitle = originalTitle;
    }
    
    @Column(name="PROGRAM_SUBTITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getProgramSubtitle() {
        return this.programSubtitle;
    }
    
    public void setProgramSubtitle(String programSubtitle) {
        this.programSubtitle = programSubtitle;
    }
    
    @Column(name="MAIN_STORY", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMainStory() {
        return this.mainStory;
    }
    
    public void setMainStory(String mainStory) {
        this.mainStory = mainStory;
    }
    
    @Column(name="MAIN_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMainImagePath() {
        return this.mainImagePath;
    }
    
    public void setMainImagePath(String mainImagePath) {
        this.mainImagePath = mainImagePath;
    }
    
    @Column(name="PROGRAM_DELIBERATION_GRADE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getProgramDeliberationGrade() {
        return this.programDeliberationGrade;
    }
    
    public void setProgramDeliberationGrade(String programDeliberationGrade) {
        this.programDeliberationGrade = programDeliberationGrade;
    }
    
    @Column(name="PROGRAM_GENRE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getProgramGenre() {
        return this.programGenre;
    }
    
    public void setProgramGenre(String programGenre) {
        this.programGenre = programGenre;
    }
    
    @Column(name="DURATION_SECOND", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getDurationSecond() {
        return this.durationSecond;
    }
    
    public void setDurationSecond(Integer durationSecond) {
        this.durationSecond = durationSecond;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="program")
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="program")
    public Set<DailyRunning> getDailyRunnings() {
        return this.dailyRunnings;
    }
    
    public void setDailyRunnings(Set<DailyRunning> dailyRunnings) {
        this.dailyRunnings = dailyRunnings;
    }




}


