package com.mindwareworks.kbs.model;

// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Programming generated by hbm2java
 */
@Entity
@Table(name = "K_PROGRAMMING", schema = "KBSTRI")
public class Programming implements java.io.Serializable {

	// Fields

	private Integer scheduleUniqueId;
	private Program program;
	private Channel channel;
	private String programTitle;
	private String programPlannedDate;
	private String programPlannedStartTime;
	private String programPlannedEndTime;
	private Integer programPlannedDurationMin;

	// Constructors

	/** default constructor */
	public Programming() {
	}

	/** minimal constructor */
	public Programming(Integer scheduleUniqueId) {
		this.scheduleUniqueId = scheduleUniqueId;
	}

	/** full constructor */
	public Programming(Integer scheduleUniqueId, Program program,
			Channel channel, String programTitle, String programPlannedDate,
			String programPlannedStartTime, String programPlannedEndTime,
			Integer programPlannedDurationMin) {
		this.scheduleUniqueId = scheduleUniqueId;
		this.program = program;
		this.channel = channel;
		this.programTitle = programTitle;
		this.programPlannedDate = programPlannedDate;
		this.programPlannedStartTime = programPlannedStartTime;
		this.programPlannedEndTime = programPlannedEndTime;
		this.programPlannedDurationMin = programPlannedDurationMin;
	}

	// Property accessors
	@Id
	@Column(name = "SCHEDULE_UNIQUE_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)
	public Integer getScheduleUniqueId() {
		return this.scheduleUniqueId;
	}

	public void setScheduleUniqueId(Integer scheduleUniqueId) {
		this.scheduleUniqueId = scheduleUniqueId;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "CONTENT_ID", unique = false, nullable = true, insertable = true, updatable = true)
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "CHANNEL_CODE", unique = false, nullable = true, insertable = true, updatable = true)
	public Channel getChannel() {
		return this.channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	@Column(name = "PROGRAM_TITLE", unique = false, nullable = true, insertable = true, updatable = true, length = 100)
	public String getProgramTitle() {
		return this.programTitle;
	}

	public void setProgramTitle(String programTitle) {
		this.programTitle = programTitle;
	}

	@Column(name = "PROGRAM_PLANNED_DATE", unique = false, nullable = true, insertable = true, updatable = true, length = 8)
	public String getProgramPlannedDate() {
		return this.programPlannedDate;
	}

	public void setProgramPlannedDate(String programPlannedDate) {
		this.programPlannedDate = programPlannedDate;
	}

	@Column(name = "PROGRAM_PLANNED_START_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 6)
	public String getProgramPlannedStartTime() {
		return this.programPlannedStartTime;
	}

	public void setProgramPlannedStartTime(String programPlannedStartTime) {
		this.programPlannedStartTime = programPlannedStartTime;
	}

	@Column(name = "PROGRAM_PLANNED_END_TIME", unique = false, nullable = true, insertable = true, updatable = true, length = 6)
	public String getProgramPlannedEndTime() {
		return this.programPlannedEndTime;
	}

	public void setProgramPlannedEndTime(String programPlannedEndTime) {
		this.programPlannedEndTime = programPlannedEndTime;
	}

	@Column(name = "PROGRAM_PLANNED_DURATION_MIN", unique = false, nullable = true, insertable = true, updatable = true, precision = 0)
	public Integer getProgramPlannedDurationMin() {
		return this.programPlannedDurationMin;
	}

	public void setProgramPlannedDurationMin(Integer programPlannedDurationMin) {
		this.programPlannedDurationMin = programPlannedDurationMin;
	}

}
