package com.mindwareworks.kbs.model;

// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "K_QUESTION", schema = "KBSTRI")
@org.hibernate.annotations.BatchSize(size=10)
public class Question implements java.io.Serializable {

	// Fields

	private Integer questionId;
	private Integer point;
	private String questionContents;
	private String questionType;

	private Set<AnswerExample> answerExamples = new HashSet<AnswerExample>(0);
	private CorrectAnswer correctAnswer;

	// Constructors

	/** default constructor */
	public Question() {
	}

	/** minimal constructor */
	public Question(Integer questionId) {
		this.questionId = questionId;
	}

	

	// Property accessors
	@Id
	@Column(name = "QUESTION_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)
	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	@Column(name = "POINT", unique = false, nullable = true, insertable = true, updatable = true, precision = 0)
	public Integer getPoint() {
		return this.point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

	@Column(name = "QUESTION_CONTENTS", unique = false, nullable = true, insertable = true, updatable = true)
	public String getQuestionContents() {
		return this.questionContents;
	}

	public void setQuestionContents(String questionContents) {
		this.questionContents = questionContents;
	}

	@Column(name = "QUESTION_TYPE", unique = false, nullable = true, insertable = true, updatable = true, length = 1)
	public String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(String questionType) {
		this.questionType = questionType;
	}

	@OneToMany(fetch=FetchType.LAZY)
	@JoinColumn(name="question_id")
	@org.hibernate.annotations.BatchSize(size=10)
	public Set<AnswerExample> getAnswerExamples() {
		return this.answerExamples;
	}

	public void setAnswerExamples(Set<AnswerExample> answerExamples) {
		this.answerExamples = answerExamples;
	}
	
	@OneToOne(fetch=FetchType.LAZY)
	@NotFound(action=NotFoundAction.IGNORE)
	@JoinColumn(name="question_id")
	public CorrectAnswer getCorrectAnswer() {
		return this.correctAnswer;
	}

	public void setCorrectAnswer(CorrectAnswer correctAnswer) {
		this.correctAnswer = correctAnswer;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append("[");
		buffer.append("questionId").append("='").append(getQuestionId())
				.append("' ");
		buffer.append("point").append("='").append(getPoint()).append("' ");
		buffer.append("questionContents").append("='")
				.append(getQuestionContents()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}
}
