package com.mindwareworks.kbs.model;

// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuizParticipation generated by hbm2java
 */
@Entity
@Table(name = "K_QUIZ_PARTICIPATION", schema = "KBSTRI")
public class QuizParticipation implements java.io.Serializable {

	// Fields

	private QuizParticipationId id;
	private Member member;
	private Question question;
	private String answer;

	// Constructors

	/** default constructor */
	public QuizParticipation() {
	}

	/** minimal constructor */
	public QuizParticipation(QuizParticipationId id, Member member,
			Question question) {
		this.id = id;
		this.member = member;
		this.question = question;
	}

	/** full constructor */
	public QuizParticipation(QuizParticipationId id, Member member,
			Question relatedQuiz, String answer) {
		this.id = id;
		this.member = member;
		this.question = question;
		this.answer = answer;
	}

	// Property accessors
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "memberid", column = @Column(name = "MEMBERID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)),
			@AttributeOverride(name = "questionId", column = @Column(name = "QUESTION_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)),
			@AttributeOverride(name = "contentId", column = @Column(name = "CONTENT_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)) })
	public QuizParticipationId getId() {
		return this.id;
	}

	public void setId(QuizParticipationId id) {
		this.id = id;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "MEMBERID", unique = false, nullable = false, insertable = false, updatable = false)
	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	@ManyToOne(cascade = {}, fetch = FetchType.LAZY)
	@JoinColumn(name = "question_id", unique = false, nullable = false, insertable = false, updatable = false)
	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	@Column(name = "ANSWER", unique = false, nullable = true, insertable = true, updatable = true)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
