package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Recipe generated by hbm2java
 */
@Entity
@Table(name="K_RECIPE"
    ,schema="KBSTRI"
)
@org.hibernate.annotations.BatchSize(size=10)
public class Recipe  implements java.io.Serializable {

    // Fields    

     private Integer recipeId;
     private String menuTitle;
     private String menuDetail;
     private String menuImagePath;
     private String ingredient;
     private String ingredientImagePath;
     private String cooking;
     private Integer cookingTime;
     private String ingredientDetail;
     private Set<RelatedRecipe> relatedRecipes = new HashSet<RelatedRecipe>(0);

     // Constructors

    /** default constructor */
    public Recipe() {
    }

	/** minimal constructor */
    public Recipe(Integer recipeId) {
        this.recipeId = recipeId;
    }
    /** full constructor */
    public Recipe(Integer recipeId, String menuTitle, String menuDetail, String menuImagePath, String ingredient, String ingredientImagePath, String cooking, Integer cookingTime, String ingredientDetail, Set<RelatedRecipe> relatedRecipes) {
       this.recipeId = recipeId;
       this.menuTitle = menuTitle;
       this.menuDetail = menuDetail;
       this.menuImagePath = menuImagePath;
       this.ingredient = ingredient;
       this.ingredientImagePath = ingredientImagePath;
       this.cooking = cooking;
       this.cookingTime = cookingTime;
       this.ingredientDetail = ingredientDetail;
       this.relatedRecipes = relatedRecipes;
    }
   
    // Property accessors
     @Id
    
    @Column(name="RECIPE_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getRecipeId() {
        return this.recipeId;
    }
    
    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }
    
    @Column(name="MENU_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMenuTitle() {
        return this.menuTitle;
    }
    
    public void setMenuTitle(String menuTitle) {
        this.menuTitle = menuTitle;
    }
    
    @Column(name="MENU_DETAIL", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMenuDetail() {
        return this.menuDetail;
    }
    
    public void setMenuDetail(String menuDetail) {
        this.menuDetail = menuDetail;
    }
    
    @Column(name="MENU_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMenuImagePath() {
        return this.menuImagePath;
    }
    
    public void setMenuImagePath(String menuImagePath) {
        this.menuImagePath = menuImagePath;
    }
    
    @Column(name="INGREDIENT", unique=false, nullable=true, insertable=true, updatable=true)
    public String getIngredient() {
        return this.ingredient;
    }
    
    public void setIngredient(String ingredient) {
        this.ingredient = ingredient;
    }
    
    @Column(name="INGREDIENT_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getIngredientImagePath() {
        return this.ingredientImagePath;
    }
    
    public void setIngredientImagePath(String ingredientImagePath) {
        this.ingredientImagePath = ingredientImagePath;
    }
    
    @Column(name="COOKING", unique=false, nullable=true, insertable=true, updatable=true)
    public String getCooking() {
        return this.cooking;
    }
    
    public void setCooking(String cooking) {
        this.cooking = cooking;
    }
    
    @Column(name="COOKING_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getCookingTime() {
        return this.cookingTime;
    }
    
    public void setCookingTime(Integer cookingTime) {
        this.cookingTime = cookingTime;
    }
    
    @Column(name="INGREDIENT_DETAIL", unique=false, nullable=true, insertable=true, updatable=true)
    public String getIngredientDetail() {
        return this.ingredientDetail;
    }
    
    public void setIngredientDetail(String ingredientDetail) {
        this.ingredientDetail = ingredientDetail;
    }
    @OneToMany(mappedBy="content")
    @org.hibernate.annotations.Fetch(org.hibernate.annotations.FetchMode.SUBSELECT)
    public Set<RelatedRecipe> getRelatedRecipes() {
        return this.relatedRecipes;
    }
    
    public void setRelatedRecipes(Set<RelatedRecipe> relatedRecipes) {
        this.relatedRecipes = relatedRecipes;
    }




}


