package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Video generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_VIDEO"
    ,schema="KBSTRI"
)
public class RelatedVideo  implements java.io.Serializable {

    // Fields    

     private RelatedVideoId id;
     private Content content;
     private Video video;
     // Constructors

    /** default constructor */
    public RelatedVideo() {
    }

	/** minimal constructor */
    public RelatedVideo(RelatedVideoId id) {
        this.id = id;
    }
    
    // Property accessors
    @EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "videoId", column = @Column(name = "VIDEO_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)),
			@AttributeOverride(name = "contentId", column = @Column(name = "CONTENT_ID", unique = false, nullable = false, insertable = true, updatable = true, precision = 0)) })
	public RelatedVideoId getId() {
        return this.id;
    }
    
    public void setId(RelatedVideoId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
   
    @ManyToOne(cascade={},
            fetch=FetchType.LAZY)
        
    @JoinColumn(name="VIDEO_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Video getVideo() {
		return video;
	}

	public void setVideo(Video video) {
		this.video = video;
	}

    



}


