package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatedScript generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_SCRIPT"
    ,schema="KBSTRI"
)
public class RelatedScript  implements java.io.Serializable {

    // Fields    

     private RelatedScriptId id;
     private Script script;
     private Content content;

     // Constructors

    /** default constructor */
    public RelatedScript() {
    }

	/** minimal constructor */
    public RelatedScript(RelatedScriptId id, Script script, Content content) {
        this.id = id;
        this.script =script;
        this.content = content;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="scriptId", column=@Column(name="SCRIPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public RelatedScriptId getId() {
        return this.id;
    }
    
    public void setId(RelatedScriptId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.EAGER)
    
    @JoinColumn(name="SCRIPT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Script getScript() {
        return this.script;
    }
    
    public void setScript(Script script) {
        this.script = script;
    }
@ManyToOne(cascade={},
        fetch=FetchType.EAGER)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    




}


