package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatedProductId generated by hbm2java
 */
@Embeddable
public class RelatedVideoId  implements java.io.Serializable {

    // Fields    

     private Long videoId;
     private Long contentId;

     // Constructors

    /** default constructor */
    public RelatedVideoId() {
    }

    /** full constructor */
    public RelatedVideoId(Long videoId, Long contentId) {
       this.videoId = videoId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="VIDEO_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Long getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Long videoId) {
        this.videoId = videoId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Long getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }




}


