package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatedScriptId generated by hbm2java
 */
@Embeddable
public class RelatedScriptId  implements java.io.Serializable {

    // Fields    

     private Integer scriptId;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public RelatedScriptId() {
    }

    /** full constructor */
    public RelatedScriptId(Integer scriptId, Integer contentId) {
       this.scriptId = scriptId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="SCRIPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getScriptId() {
        return this.scriptId;
    }
    
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


