package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatedContent generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_CONTENT"
    ,schema="KBSTRI"
)
public class RelatedContent  implements java.io.Serializable {

    // Fields    

     private RelatedContentId id;
     private Content content;

     // Constructors

    /** default constructor */
    public RelatedContent() {
    }

    /** full constructor */
    public RelatedContent(RelatedContentId id, Content content) {
       this.id = id;
       this.content = content;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="relatedContentId", column=@Column(name="RELATED_CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public RelatedContentId getId() {
        return this.id;
    }
    
    public void setId(RelatedContentId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }




}


