package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SecondaryTable;
import javax.persistence.Table;

/**
 * Script generated by hbm2java
 */
@Entity
@Table(name="K_SCRIPT"
    ,schema="KBSTRI"
)
@SecondaryTable(name="K_RELATED_SCRIPT")
public class Script  implements java.io.Serializable {

    // Fields    

     private Integer scriptId;
     private Content content;
     private String scriptTitle;
     private String scriptFilePath;
     private String scriptFullText;

     // Constructors

    /** default constructor */
    public Script() {
    }

	/** minimal constructor */
    public Script(Integer scriptId) {
        this.scriptId = scriptId;
    }
    /** full constructor */
    public Script(Integer scriptId, Content content, String scriptTitle, String scriptFilePath, String scriptFullText) {
       this.scriptId = scriptId;
       this.content = content;
       this.scriptTitle = scriptTitle;
       this.scriptFilePath = scriptFilePath;
       this.scriptFullText = scriptFullText;
    }
   
    // Property accessors
     @Id
    
    @Column(name="SCRIPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getScriptId() {
        return this.scriptId;
    }
    
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }
    
	@ManyToOne
	@JoinColumn(table="K_RELATED_SCRIPT",name="CONTENT_ID")
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="SCRIPT_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptTitle() {
        return this.scriptTitle;
    }
    
    public void setScriptTitle(String scriptTitle) {
        this.scriptTitle = scriptTitle;
    }
    
    @Column(name="SCRIPT_FILE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptFilePath() {
        return this.scriptFilePath;
    }
    
    public void setScriptFilePath(String scriptFilePath) {
        this.scriptFilePath = scriptFilePath;
    }
    
    @Column(name="SCRIPT_FULL_TEXT", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptFullText() {
        return this.scriptFullText;
    }
    
    public void setScriptFullText(String scriptFullText) {
        this.scriptFullText = scriptFullText;
    }




}


