package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Script generated by hbm2java
 */
@Entity
@Table(name="K_SCRIPT"
    ,schema="KBSTRI"
)

@org.hibernate.annotations.GenericGenerator(name="sequence",strategy="sequence",
parameters={@org.hibernate.annotations.Parameter(name="sequence", value="SEQ_SCRIPT")})
public class Script  implements java.io.Serializable {

    // Fields    

     private Integer scriptId;
     private String scriptTitle;
     private String scriptFilePath;
     private String scriptFullText;
     private Set<RelatedScript> relatedScripts = new HashSet<RelatedScript>(0);

     // Constructors

    /** default constructor */
    public Script() {
    }

	/** minimal constructor */
    public Script(Integer scriptId) {
        this.scriptId = scriptId;
    }
    /** full constructor */
    public Script(String scriptTitle, String scriptFilePath, String scriptFullText) {
       this.scriptTitle = scriptTitle;
       this.scriptFilePath = scriptFilePath;
       this.scriptFullText = scriptFullText;
    }
   
    // Property accessors
    @Id    
    @GeneratedValue(generator="sequence")
    @Column(name="SCRIPT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getScriptId() {
        return this.scriptId;
    }
    
    public void setScriptId(Integer scriptId) {
        this.scriptId = scriptId;
    }
    
//    @OneToMany(mappedBy="script")
//    @org.hibernate.annotations.BatchSize(size=10)
//    public Set<RelatedScript> getRelatedScripts() {
//        return this.relatedScripts;
//    }
//    
//    public void setRelatedScripts(Set<RelatedScript> relatedScripts) {
//        this.relatedScripts = relatedScripts;
//    }
    
    @Column(name="SCRIPT_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptTitle() {
        return this.scriptTitle;
    }
    
    public void setScriptTitle(String scriptTitle) {
        this.scriptTitle = scriptTitle;
    }
    
    @Column(name="SCRIPT_FILE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptFilePath() {
        return this.scriptFilePath;
    }
    
    public void setScriptFilePath(String scriptFilePath) {
        this.scriptFilePath = scriptFilePath;
    }
    
    @Column(name="SCRIPT_FULL_TEXT", unique=false, nullable=true, insertable=true, updatable=true)
    public String getScriptFullText() {
        return this.scriptFullText;
    }
    
    public void setScriptFullText(String scriptFullText) {
        this.scriptFullText = scriptFullText;
    }




}


