package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Segment generated by hbm2java
 */
@Entity
@Table(name="K_SEGMENT"
    ,schema="KBSTRI"
)
public class Segment  implements java.io.Serializable {

    // Fields    

     private Integer contentId;
     private Content content;
     private SegmentCode segmentCode;
     private String programId;
     private String segmentId;
     private String segmentTitle;
     private String mainStory;
     private String mainImagePath;
     private Integer durationSecond;

     // Constructors

    /** default constructor */
    public Segment() {
    }

	/** minimal constructor */
    public Segment(Integer contentId, Content content, String programId, String segmentId) {
        this.contentId = contentId;
        this.content = content;
        this.programId = programId;
        this.segmentId = segmentId;
    }
    /** full constructor */
    public Segment(Integer contentId, Content content, SegmentCode segmentCode, String programId, String segmentId, String segmentTitle, String mainStory, String mainImagePath, Integer durationSecond) {
       this.contentId = contentId;
       this.content = content;
       this.segmentCode = segmentCode;
       this.programId = programId;
       this.segmentId = segmentId;
       this.segmentTitle = segmentTitle;
       this.mainStory = mainStory;
       this.mainImagePath = mainImagePath;
       this.durationSecond = durationSecond;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=true, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="SEGMENT_CODE", unique=false, nullable=true, insertable=true, updatable=true)
    public SegmentCode getSegmentCode() {
        return this.segmentCode;
    }
    
    public void setSegmentCode(SegmentCode segmentCode) {
        this.segmentCode = segmentCode;
    }
    
    @Column(name="PROGRAM_ID", unique=false, nullable=false, insertable=true, updatable=true, length=20)
    public String getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(String programId) {
        this.programId = programId;
    }
    
    @Column(name="SEGMENT_ID", unique=false, nullable=false, insertable=true, updatable=true, length=25)
    public String getSegmentId() {
        return this.segmentId;
    }
    
    public void setSegmentId(String segmentId) {
        this.segmentId = segmentId;
    }
    
    @Column(name="SEGMENT_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getSegmentTitle() {
        return this.segmentTitle;
    }
    
    public void setSegmentTitle(String segmentTitle) {
        this.segmentTitle = segmentTitle;
    }
    
    @Column(name="MAIN_STORY", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMainStory() {
        return this.mainStory;
    }
    
    public void setMainStory(String mainStory) {
        this.mainStory = mainStory;
    }
    
    @Column(name="MAIN_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMainImagePath() {
        return this.mainImagePath;
    }
    
    public void setMainImagePath(String mainImagePath) {
        this.mainImagePath = mainImagePath;
    }
    
    @Column(name="DURATION_SECOND", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getDurationSecond() {
        return this.durationSecond;
    }
    
    public void setDurationSecond(Integer durationSecond) {
        this.durationSecond = durationSecond;
    }




}


