package com.mindwareworks.kbs.model;
// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Video generated by hbm2java
 */
@Entity
@Table(name="K_VIDEO"
    ,schema="KBSTRI"
)
public class Video  implements java.io.Serializable {

    // Fields    

     private Integer videoId;
     private Content content;
     private String thumbnailFilePath;
     private String registrationDate;
     private Set<VideoFile> videoFiles = new HashSet<VideoFile>(0);
     // Constructors

    /** default constructor */
    public Video() {
    }

	/** minimal constructor */
    public Video(Integer videoId) {
        this.videoId = videoId;
    }
    /** full constructor */
    public Video(Integer videoId, Content content, String thumbnailFilePath, String registrationDate, Set<VideoFile> videoFiles) {
       this.videoId = videoId;
       this.content = content;
       this.thumbnailFilePath = thumbnailFilePath;
       this.registrationDate = registrationDate;
       this.videoFiles = videoFiles;
    }
   
    // Property accessors
     @Id
    
    @Column(name="VIDEO_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=true, insertable=true, updatable=true)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="THUMBNAIL_FILE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getThumbnailFilePath() {
        return this.thumbnailFilePath;
    }
    
    public void setThumbnailFilePath(String thumbnailFilePath) {
        this.thumbnailFilePath = thumbnailFilePath;
    }
    
    @Column(name="REGISTRATION_DATE", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(String registrationDate) {
        this.registrationDate = registrationDate;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="video")
    public Set<VideoFile> getVideoFiles() {
        return this.videoFiles;
    }
    
    public void setVideoFiles(Set<VideoFile> videoFiles) {
        this.videoFiles = videoFiles;
    }




}


