// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswerExampleId generated by hbm2java
 */
@Embeddable
public class AnswerExampleId  implements java.io.Serializable {

    // Fields    

     private Integer questionId;
     private Integer exampleNumber;

     // Constructors

    /** default constructor */
    public AnswerExampleId() {
    }

    /** full constructor */
    public AnswerExampleId(Integer questionId, Integer exampleNumber) {
       this.questionId = questionId;
       this.exampleNumber = exampleNumber;
    }
   
    // Property accessors

    @Column(name="QUESTION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    @Column(name="EXAMPLE_NUMBER", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getExampleNumber() {
        return this.exampleNumber;
    }
    
    public void setExampleNumber(Integer exampleNumber) {
        this.exampleNumber = exampleNumber;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("questionId").append("='").append(getQuestionId()).append("' ");			
      buffer.append("exampleNumber").append("='").append(getExampleNumber()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }



}


