// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppEncodingId generated by hbm2java
 */
@Embeddable
public class AppEncodingId  implements java.io.Serializable {

    // Fields    

     private String appid;
     private String version;

     // Constructors

    /** default constructor */
    public AppEncodingId() {
    }

    /** full constructor */
    public AppEncodingId(String appid, String version) {
       this.appid = appid;
       this.version = version;
    }
   
    // Property accessors

    @Column(name="APPID", unique=false, nullable=false, insertable=true, updatable=true, length=64)
    public String getAppid() {
        return this.appid;
    }
    
    public void setAppid(String appid) {
        this.appid = appid;
    }

    @Column(name="VERSION", unique=false, nullable=false, insertable=true, updatable=true, length=32)
    public String getVersion() {
        return this.version;
    }
    
    public void setVersion(String version) {
        this.version = version;
    }




}


