// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppEncoding generated by hbm2java
 */
@Entity
@Table(name="K_APP_ENCODING"
    ,schema="KBSTRI"
)
public class AppEncoding  implements java.io.Serializable {

    // Fields    

     private AppEncodingId id;
     private Encoding encoding;

     // Constructors

    /** default constructor */
    public AppEncoding() {
    }

    /** full constructor */
    public AppEncoding(AppEncodingId id, Encoding encoding) {
       this.id = id;
       this.encoding = encoding;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="appid", column=@Column(name="APPID", unique=false, nullable=false, insertable=true, updatable=true, length=64) ), 
        @AttributeOverride(name="version", column=@Column(name="VERSION", unique=false, nullable=false, insertable=true, updatable=true, length=32) ) } )
    public AppEncodingId getId() {
        return this.id;
    }
    
    public void setId(AppEncodingId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="ENCODING_ID", unique=false, nullable=false, insertable=true, updatable=true)
    public Encoding getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(Encoding encoding) {
        this.encoding = encoding;
    }




}


