// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Channel generated by hbm2java
 */
@Entity
@Table(name="K_CHANNEL"
    ,schema="KBSTRI"
)
public class Channel  implements java.io.Serializable {

    // Fields    

     private String channelCode;
     private String mediaName;
     private String channelName;
     private String channelGrade;
     private String channelDescription;
     private String channelImagePath;
     private String liveStreamUrl;
     private String channelAuthority;
     private Set<DailyRunning> dailyRunnings = new HashSet<DailyRunning>(0);
     private Set<Programming> programmings = new HashSet<Programming>(0);

     // Constructors

    /** default constructor */
    public Channel() {
    }

	/** minimal constructor */
    public Channel(String channelCode) {
        this.channelCode = channelCode;
    }
    /** full constructor */
    public Channel(String channelCode, String mediaName, String channelName, String channelGrade, String channelDescription, String channelImagePath, String liveStreamUrl, String channelAuthority, Set<DailyRunning> dailyRunnings, Set<Programming> programmings) {
       this.channelCode = channelCode;
       this.mediaName = mediaName;
       this.channelName = channelName;
       this.channelGrade = channelGrade;
       this.channelDescription = channelDescription;
       this.channelImagePath = channelImagePath;
       this.liveStreamUrl = liveStreamUrl;
       this.channelAuthority = channelAuthority;
       this.dailyRunnings = dailyRunnings;
       this.programmings = programmings;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CHANNEL_CODE", unique=false, nullable=false, insertable=true, updatable=true, length=2)
    public String getChannelCode() {
        return this.channelCode;
    }
    
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }
    
    @Column(name="MEDIA_NAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getMediaName() {
        return this.mediaName;
    }
    
    public void setMediaName(String mediaName) {
        this.mediaName = mediaName;
    }
    
    @Column(name="CHANNEL_NAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelName() {
        return this.channelName;
    }
    
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }
    
    @Column(name="CHANNEL_GRADE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelGrade() {
        return this.channelGrade;
    }
    
    public void setChannelGrade(String channelGrade) {
        this.channelGrade = channelGrade;
    }
    
    @Column(name="CHANNEL_DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelDescription() {
        return this.channelDescription;
    }
    
    public void setChannelDescription(String channelDescription) {
        this.channelDescription = channelDescription;
    }
    
    @Column(name="CHANNEL_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelImagePath() {
        return this.channelImagePath;
    }
    
    public void setChannelImagePath(String channelImagePath) {
        this.channelImagePath = channelImagePath;
    }
    
    @Column(name="LIVE_STREAM_URL", unique=false, nullable=true, insertable=true, updatable=true)
    public String getLiveStreamUrl() {
        return this.liveStreamUrl;
    }
    
    public void setLiveStreamUrl(String liveStreamUrl) {
        this.liveStreamUrl = liveStreamUrl;
    }
    
    @Column(name="CHANNEL_AUTHORITY", unique=false, nullable=true, insertable=true, updatable=true, length=2)
    public String getChannelAuthority() {
        return this.channelAuthority;
    }
    
    public void setChannelAuthority(String channelAuthority) {
        this.channelAuthority = channelAuthority;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="channel")
    public Set<DailyRunning> getDailyRunnings() {
        return this.dailyRunnings;
    }
    
    public void setDailyRunnings(Set<DailyRunning> dailyRunnings) {
        this.dailyRunnings = dailyRunnings;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="channel")
    public Set<Programming> getProgrammings() {
        return this.programmings;
    }
    
    public void setProgrammings(Set<Programming> programmings) {
        this.programmings = programmings;
    }




}


