// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContentRanking generated by hbm2java
 */
@Entity
@Table(name="K_CONTENT_RANKING"
    ,schema="KBSTRI"
)
public class ContentRanking  implements java.io.Serializable {

    // Fields    

     private ContentRankingId id;
     private Content content;

     // Constructors

    /** default constructor */
    public ContentRanking() {
    }

    /** full constructor */
    public ContentRanking(ContentRankingId id, Content content) {
       this.id = id;
       this.content = content;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="rankingType", column=@Column(name="RANKING_TYPE", unique=false, nullable=false, insertable=true, updatable=true, length=1) ), 
        @AttributeOverride(name="ranking", column=@Column(name="RANKING", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public ContentRankingId getId() {
        return this.id;
    }
    
    public void setId(ContentRankingId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }




}


