// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomChannel generated by hbm2java
 */
@Entity
@Table(name="K_CUSTOM_CHANNEL"
    ,schema="KBSTRI"
)
public class CustomChannel  implements java.io.Serializable {

    // Fields    

     private Integer channelId;
     private Member member;
     private String channelTitle;
     private String channelDescription;
     private BigDecimal bookmarkCount;
     private String registrationDateTime;
     private String channelMainImagePath;
     private String openYn;
     private Set<Member> bookmarkingMembers = new HashSet<Member>(0);
     private Set<ChannelItem> channelItems = new HashSet<ChannelItem>(0);

     // Constructors

    /** default constructor */
    public CustomChannel() {
    }

	/** minimal constructor */
    public CustomChannel(Integer channelId) {
        this.channelId = channelId;
    }
    /** full constructor */
    public CustomChannel(Integer channelId, Member member, String channelTitle, String channelDescription, BigDecimal bookmarkCount, String registrationDateTime, String channelMainImagePath, String openYn, Set<Member> bookmarkingMembers, Set<ChannelItem> channelItems) {
       this.channelId = channelId;
       this.member = member;
       this.channelTitle = channelTitle;
       this.channelDescription = channelDescription;
       this.bookmarkCount = bookmarkCount;
       this.registrationDateTime = registrationDateTime;
       this.channelMainImagePath = channelMainImagePath;
       this.openYn = openYn;
       this.bookmarkingMembers = bookmarkingMembers;
       this.channelItems = channelItems;
    }
   
    // Property accessors
     @Id
    
    @Column(name="CHANNEL_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getChannelId() {
        return this.channelId;
    }
    
    public void setChannelId(Integer channelId) {
        this.channelId = channelId;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="MEMBERID", unique=false, nullable=true, insertable=true, updatable=true)
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    
    @Column(name="CHANNEL_TITLE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelTitle() {
        return this.channelTitle;
    }
    
    public void setChannelTitle(String channelTitle) {
        this.channelTitle = channelTitle;
    }
    
    @Column(name="CHANNEL_DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelDescription() {
        return this.channelDescription;
    }
    
    public void setChannelDescription(String channelDescription) {
        this.channelDescription = channelDescription;
    }
    
    @Column(name="BOOKMARK_COUNT", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public BigDecimal getBookmarkCount() {
        return this.bookmarkCount;
    }
    
    public void setBookmarkCount(BigDecimal bookmarkCount) {
        this.bookmarkCount = bookmarkCount;
    }
    
    @Column(name="REGISTRATION_DATE_TIME", unique=false, nullable=true, insertable=true, updatable=true, length=14)
    public String getRegistrationDateTime() {
        return this.registrationDateTime;
    }
    
    public void setRegistrationDateTime(String registrationDateTime) {
        this.registrationDateTime = registrationDateTime;
    }
    
    @Column(name="CHANNEL_MAIN_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getChannelMainImagePath() {
        return this.channelMainImagePath;
    }
    
    public void setChannelMainImagePath(String channelMainImagePath) {
        this.channelMainImagePath = channelMainImagePath;
    }
    
    @Column(name="OPEN_YN", unique=false, nullable=true, insertable=true, updatable=true, length=1)
    public String getOpenYn() {
        return this.openYn;
    }
    
    public void setOpenYn(String openYn) {
        this.openYn = openYn;
    }
    @ManyToMany(cascade={}, fetch=FetchType.LAZY)
    @JoinTable(name="K_CUSTOM_CHANNEL_BOOKMARK", joinColumns = { 
        @JoinColumn(name="CHANNEL_ID", unique=false, nullable=false, insertable=true, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="MEMBERID", unique=false, nullable=false, insertable=true, updatable=false) })
    public Set<Member> getBookmarkingMembers() {
        return this.bookmarkingMembers;
    }
    
    public void setBookmarkingMembers(Set<Member> bookmarkingMembers) {
        this.bookmarkingMembers = bookmarkingMembers;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="customChannel")
    public Set<ChannelItem> getChannelItems() {
        return this.channelItems;
    }
    
    public void setChannelItems(Set<ChannelItem> channelItems) {
        this.channelItems = channelItems;
    }




}


