// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name="K_EVENT"
    ,schema="KBSTRI"
)
public class Event  implements java.io.Serializable {

    // Fields    

     private Integer eventId;
     private String eventUrl;
     private String eventTitle;
     private String eventContents;
     private String eventType;
     private Set<Content> contents = new HashSet<Content>(0);

     // Constructors

    /** default constructor */
    public Event() {
    }

	/** minimal constructor */
    public Event(Integer eventId) {
        this.eventId = eventId;
    }
    /** full constructor */
    public Event(Integer eventId, String eventUrl, String eventTitle, String eventContents, String eventType, Set<Content> contents) {
       this.eventId = eventId;
       this.eventUrl = eventUrl;
       this.eventTitle = eventTitle;
       this.eventContents = eventContents;
       this.eventType = eventType;
       this.contents = contents;
    }
   
    // Property accessors
     @Id
    
    @Column(name="EVENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    
    @Column(name="EVENT_URL", unique=false, nullable=true, insertable=true, updatable=true, length=100)
    public String getEventUrl() {
        return this.eventUrl;
    }
    
    public void setEventUrl(String eventUrl) {
        this.eventUrl = eventUrl;
    }
    
    @Column(name="EVENT_TITLE", unique=false, nullable=true, insertable=true, updatable=true, length=100)
    public String getEventTitle() {
        return this.eventTitle;
    }
    
    public void setEventTitle(String eventTitle) {
        this.eventTitle = eventTitle;
    }
    
    @Column(name="EVENT_CONTENTS", unique=false, nullable=true, insertable=true, updatable=true)
    public String getEventContents() {
        return this.eventContents;
    }
    
    public void setEventContents(String eventContents) {
        this.eventContents = eventContents;
    }
    
    @Column(name="EVENT_TYPE", unique=false, nullable=true, insertable=true, updatable=true)
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }
    @ManyToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="events")
    public Set<Content> getContents() {
        return this.contents;
    }
    
    public void setContents(Set<Content> contents) {
        this.contents = contents;
    }




}


