// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LiveCaption generated by hbm2java
 */
@Entity
@Table(name="K_LIVE_CAPTION"
    ,schema="KBSTRI"
)
public class LiveCaption  implements java.io.Serializable {

    // Fields    

     private LiveCaptionId id;
     private String captionFormat;
     private String captionContents;

     // Constructors

    /** default constructor */
    public LiveCaption() {
    }

	/** minimal constructor */
    public LiveCaption(LiveCaptionId id) {
        this.id = id;
    }
    /** full constructor */
    public LiveCaption(LiveCaptionId id, String captionFormat, String captionContents) {
       this.id = id;
       this.captionFormat = captionFormat;
       this.captionContents = captionContents;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="captionSeq", column=@Column(name="CAPTION_SEQ", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public LiveCaptionId getId() {
        return this.id;
    }
    
    public void setId(LiveCaptionId id) {
        this.id = id;
    }
    
    @Column(name="CAPTION_FORMAT", unique=false, nullable=true, insertable=true, updatable=true, length=8)
    public String getCaptionFormat() {
        return this.captionFormat;
    }
    
    public void setCaptionFormat(String captionFormat) {
        this.captionFormat = captionFormat;
    }
    
    @Column(name="CAPTION_CONTENTS", unique=false, nullable=true, insertable=true, updatable=true)
    public String getCaptionContents() {
        return this.captionContents;
    }
    
    public void setCaptionContents(String captionContents) {
        this.captionContents = captionContents;
    }




}


