// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectCategoryId generated by hbm2java
 */
@Embeddable
public class ObjectCategoryId  implements java.io.Serializable {

    // Fields    

     private Integer objid;
     private Integer categoryid;

     // Constructors

    /** default constructor */
    public ObjectCategoryId() {
    }

    /** full constructor */
    public ObjectCategoryId(Integer objid, Integer categoryid) {
       this.objid = objid;
       this.categoryid = categoryid;
    }
   
    // Property accessors

    @Column(name="OBJID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getObjid() {
        return this.objid;
    }
    
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    @Column(name="CATEGORYID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }




}


