// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="K_PERSON"
    ,schema="KBSTRI"
)
public class Person  implements java.io.Serializable {

    // Fields    

     private Integer personId;
     private String personName;
     private String personImagePath;
     private Serializable description;
     private Set<RelatedPerson> relatedPersons = new HashSet<RelatedPerson>(0);

     // Constructors

    /** default constructor */
    public Person() {
    }

	/** minimal constructor */
    public Person(Integer personId) {
        this.personId = personId;
    }
    /** full constructor */
    public Person(Integer personId, String personName, String personImagePath, Serializable description, Set<RelatedPerson> relatedPersons) {
       this.personId = personId;
       this.personName = personName;
       this.personImagePath = personImagePath;
       this.description = description;
       this.relatedPersons = relatedPersons;
    }
   
    // Property accessors
     @Id
    
    @Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
    
    @Column(name="PERSON_NAME", unique=false, nullable=true, insertable=true, updatable=true)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }
    
    @Column(name="PERSON_IMAGE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getPersonImagePath() {
        return this.personImagePath;
    }
    
    public void setPersonImagePath(String personImagePath) {
        this.personImagePath = personImagePath;
    }
    
    @Column(name="DESCRIPTION", unique=false, nullable=true, insertable=true, updatable=true)
    public Serializable getDescription() {
        return this.description;
    }
    
    public void setDescription(Serializable description) {
        this.description = description;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="person")
    public Set<RelatedPerson> getRelatedPersons() {
        return this.relatedPersons;
    }
    
    public void setRelatedPersons(Set<RelatedPerson> relatedPersons) {
        this.relatedPersons = relatedPersons;
    }




}


