// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuizId generated by hbm2java
 */
@Embeddable
public class QuizId  implements java.io.Serializable {

    // Fields    

     private Integer questionId;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public QuizId() {
    }

    /** full constructor */
    public QuizId(Integer questionId, Integer contentId) {
       this.questionId = questionId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="QUESTION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


