// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatedPersonId generated by hbm2java
 */
@Embeddable
public class RelatedPersonId  implements java.io.Serializable {

    // Fields    

     private Integer personId;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public RelatedPersonId() {
    }

    /** full constructor */
    public RelatedPersonId(Integer personId, Integer contentId) {
       this.personId = personId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="PERSON_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


