// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RelatedSurvey generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_SURVEY"
    ,schema="KBSTRI"
)
public class RelatedSurvey  implements java.io.Serializable {

    // Fields    

     private RelatedSurveyId id;
     private Content content;
     private Question question;
     private Integer startTime;
     private Integer endTime;
     private Set<SurveyParticipation> surveyParticipations = new HashSet<SurveyParticipation>(0);

     // Constructors

    /** default constructor */
    public RelatedSurvey() {
    }

	/** minimal constructor */
    public RelatedSurvey(RelatedSurveyId id, Content content, Question question) {
        this.id = id;
        this.content = content;
        this.question = question;
    }
    /** full constructor */
    public RelatedSurvey(RelatedSurveyId id, Content content, Question question, Integer startTime, Integer endTime, Set<SurveyParticipation> surveyParticipations) {
       this.id = id;
       this.content = content;
       this.question = question;
       this.startTime = startTime;
       this.endTime = endTime;
       this.surveyParticipations = surveyParticipations;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="questionId", column=@Column(name="QUESTION_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public RelatedSurveyId getId() {
        return this.id;
    }
    
    public void setId(RelatedSurveyId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="QUESTION_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    
    @Column(name="START_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }
    
    @Column(name="END_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="relatedSurvey")
    public Set<SurveyParticipation> getSurveyParticipations() {
        return this.surveyParticipations;
    }
    
    public void setSurveyParticipations(Set<SurveyParticipation> surveyParticipations) {
        this.surveyParticipations = surveyParticipations;
    }




}


