// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatedNews generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_NEWS"
    ,schema="KBSTRI"
)
public class RelatedNews  implements java.io.Serializable {

    // Fields    

     private RelatedNewsId id;
     private News news;
     private Content content;
     private Integer startTime;
     private Integer endTime;

     // Constructors

    /** default constructor */
    public RelatedNews() {
    }

	/** minimal constructor */
    public RelatedNews(RelatedNewsId id, News news, Content content) {
        this.id = id;
        this.news = news;
        this.content = content;
    }
    /** full constructor */
    public RelatedNews(RelatedNewsId id, News news, Content content, Integer startTime, Integer endTime) {
       this.id = id;
       this.news = news;
       this.content = content;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="newsId", column=@Column(name="NEWS_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public RelatedNewsId getId() {
        return this.id;
    }
    
    public void setId(RelatedNewsId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="NEWS_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="START_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }
    
    @Column(name="END_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }




}


