// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RelatedNewsId generated by hbm2java
 */
@Embeddable
public class RelatedNewsId  implements java.io.Serializable {

    // Fields    

     private Integer newsId;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public RelatedNewsId() {
    }

    /** full constructor */
    public RelatedNewsId(Integer newsId, Integer contentId) {
       this.newsId = newsId;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="NEWS_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getNewsId() {
        return this.newsId;
    }
    
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


