// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatedProduct generated by hbm2java
 */
@Entity
@Table(name="K_RELATED_PRODUCT"
    ,schema="KBSTRI"
)
public class RelatedProduct  implements java.io.Serializable {

    // Fields    

     private RelatedProductId id;
     private Content content;
     private Product product;
     private Integer startTime;
     private Integer endTime;

     // Constructors

    /** default constructor */
    public RelatedProduct() {
    }

	/** minimal constructor */
    public RelatedProduct(RelatedProductId id, Content content, Product product) {
        this.id = id;
        this.content = content;
        this.product = product;
    }
    /** full constructor */
    public RelatedProduct(RelatedProductId id, Content content, Product product, Integer startTime, Integer endTime) {
       this.id = id;
       this.content = content;
       this.product = product;
       this.startTime = startTime;
       this.endTime = endTime;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="PRODUCT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public RelatedProductId getId() {
        return this.id;
    }
    
    public void setId(RelatedProductId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="PRODUCT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    
    @Column(name="START_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }
    
    @Column(name="END_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }




}


