// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SeamlessId generated by hbm2java
 */
@Embeddable
public class SeamlessId  implements java.io.Serializable {

    // Fields    

     private Integer objid;
     private Integer deviceid;
     private Integer contentId;

     // Constructors

    /** default constructor */
    public SeamlessId() {
    }

    /** full constructor */
    public SeamlessId(Integer objid, Integer deviceid, Integer contentId) {
       this.objid = objid;
       this.deviceid = deviceid;
       this.contentId = contentId;
    }
   
    // Property accessors

    @Column(name="OBJID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getObjid() {
        return this.objid;
    }
    
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    @Column(name="DEVICEID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getDeviceid() {
        return this.deviceid;
    }
    
    public void setDeviceid(Integer deviceid) {
        this.deviceid = deviceid;
    }

    @Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getContentId() {
        return this.contentId;
    }
    
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }




}


