// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Seamless generated by hbm2java
 */
@Entity
@Table(name="K_SEAMLESS"
    ,schema="KBSTRI"
)
public class Seamless  implements java.io.Serializable {

    // Fields    

     private SeamlessId id;
     private Content content;
     private Integer lastViewingStartTime;
     private Integer lastViewingDateTime;

     // Constructors

    /** default constructor */
    public Seamless() {
    }

	/** minimal constructor */
    public Seamless(SeamlessId id, Content content) {
        this.id = id;
        this.content = content;
    }
    /** full constructor */
    public Seamless(SeamlessId id, Content content, Integer lastViewingStartTime, Integer lastViewingDateTime) {
       this.id = id;
       this.content = content;
       this.lastViewingStartTime = lastViewingStartTime;
       this.lastViewingDateTime = lastViewingDateTime;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="objid", column=@Column(name="OBJID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="deviceid", column=@Column(name="DEVICEID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="contentId", column=@Column(name="CONTENT_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public SeamlessId getId() {
        return this.id;
    }
    
    public void setId(SeamlessId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="CONTENT_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    
    @Column(name="LAST_VIEWING_START_TIME", unique=false, nullable=true, insertable=true, updatable=true, precision=0)
    public Integer getLastViewingStartTime() {
        return this.lastViewingStartTime;
    }
    
    public void setLastViewingStartTime(Integer lastViewingStartTime) {
        this.lastViewingStartTime = lastViewingStartTime;
    }
    
    @Column(name="LAST_VIEWING_DATE_TIME", unique=false, nullable=true, insertable=true, updatable=true, length=14)
    public Integer getLastViewingDateTime() {
        return this.lastViewingDateTime;
    }
    
    public void setLastViewingDateTime(Integer lastViewingDateTime) {
        this.lastViewingDateTime = lastViewingDateTime;
    }




}


