// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SegmentCode generated by hbm2java
 */
@Entity
@Table(name="K_SEGMENT_CODE"
    ,schema="KBSTRI"
)
public class SegmentCode  implements java.io.Serializable {

    // Fields    

     private String segmentCode;
     private ProgramCode programCode;
     private Set<Segment> segments = new HashSet<Segment>(0);

     // Constructors

    /** default constructor */
    public SegmentCode() {
    }

	/** minimal constructor */
    public SegmentCode(String segmentCode) {
        this.segmentCode = segmentCode;
    }
    /** full constructor */
    public SegmentCode(String segmentCode, ProgramCode programCode, Set<Segment> segments) {
       this.segmentCode = segmentCode;
       this.programCode = programCode;
       this.segments = segments;
    }
   
    // Property accessors
     @Id
    
    @Column(name="SEGMENT_CODE", unique=false, nullable=false, insertable=true, updatable=true, length=15)
    public String getSegmentCode() {
        return this.segmentCode;
    }
    
    public void setSegmentCode(String segmentCode) {
        this.segmentCode = segmentCode;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="PROGRAM_CODE", unique=false, nullable=true, insertable=true, updatable=true)
    public ProgramCode getProgramCode() {
        return this.programCode;
    }
    
    public void setProgramCode(ProgramCode programCode) {
        this.programCode = programCode;
    }
    @OneToMany(cascade={}, fetch=FetchType.LAZY, mappedBy="segmentCode")
    public Set<Segment> getSegments() {
        return this.segments;
    }
    
    public void setSegments(Set<Segment> segments) {
        this.segments = segments;
    }




}


