// default package
// Generated 2012. 3. 5 오후 1:52:33 by Hibernate Tools 3.2.0.beta8


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VideoFileId generated by hbm2java
 */
@Embeddable
public class VideoFileId  implements java.io.Serializable {

    // Fields    

     private Integer videoId;
     private Integer encodingId;

     // Constructors

    /** default constructor */
    public VideoFileId() {
    }

    /** full constructor */
    public VideoFileId(Integer videoId, Integer encodingId) {
       this.videoId = videoId;
       this.encodingId = encodingId;
    }
   
    // Property accessors

    @Column(name="VIDEO_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getVideoId() {
        return this.videoId;
    }
    
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    @Column(name="ENCODING_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0)
    public Integer getEncodingId() {
        return this.encodingId;
    }
    
    public void setEncodingId(Integer encodingId) {
        this.encodingId = encodingId;
    }




}


