// default package
// Generated 2012. 3. 2 오후 8:12:59 by Hibernate Tools 3.2.0.beta8


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VideoFile generated by hbm2java
 */
@Entity
@Table(name="K_VIDEO_FILE"
    ,schema="KBSTRI"
)
public class VideoFile  implements java.io.Serializable {

    // Fields    

     private VideoFileId id;
     private Encoding encoding;
     private Video video;
     private String outputFilePath;

     // Constructors

    /** default constructor */
    public VideoFile() {
    }

	/** minimal constructor */
    public VideoFile(VideoFileId id, Encoding encoding, Video video) {
        this.id = id;
        this.encoding = encoding;
        this.video = video;
    }
    /** full constructor */
    public VideoFile(VideoFileId id, Encoding encoding, Video video, String outputFilePath) {
       this.id = id;
       this.encoding = encoding;
       this.video = video;
       this.outputFilePath = outputFilePath;
    }
   
    // Property accessors
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="videoId", column=@Column(name="VIDEO_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ), 
        @AttributeOverride(name="encodingId", column=@Column(name="ENCODING_ID", unique=false, nullable=false, insertable=true, updatable=true, precision=0) ) } )
    public VideoFileId getId() {
        return this.id;
    }
    
    public void setId(VideoFileId id) {
        this.id = id;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="ENCODING_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Encoding getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(Encoding encoding) {
        this.encoding = encoding;
    }
@ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
    @JoinColumn(name="VIDEO_ID", unique=false, nullable=false, insertable=false, updatable=false)
    public Video getVideo() {
        return this.video;
    }
    
    public void setVideo(Video video) {
        this.video = video;
    }
    
    @Column(name="OUTPUT_FILE_PATH", unique=false, nullable=true, insertable=true, updatable=true)
    public String getOutputFilePath() {
        return this.outputFilePath;
    }
    
    public void setOutputFilePath(String outputFilePath) {
        this.outputFilePath = outputFilePath;
    }




}


